// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xefbqgucxzgkhxgctqxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlZmJxZ3VjeHpna2h4Z2N0cXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1OTQzMjUsImV4cCI6MjA3NzE3MDMyNX0.-NR6TfR6Zym8Baw1pd21v3CzAHTOHHUU3CWwXs6SoDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});