// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhhdxwgrmcdsapbuvelx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oaGR4d2dybWNkc2FwYnV2ZWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NjAwNDIsImV4cCI6MjA3MTQzNjA0Mn0.GYfN5gGPUth2oo3GTvch9vOZa6lI-Ll93E9-x6M0-iM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: sessionStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});